version: '3.8'

services:
  backend:
    extends:
      file: docker-compose.yml
      service: backend
      image: edu-hub-backend:prod
    environment:
      - NODE_ENV=production
    command: npm start